# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2191d2efe7bde83173baac09af2ce00991d2a69dd3084ea89fec70c1783801bc4bdf2868a3ccc0e0bff6b9d972fe350942d3a566199d674664506467374d2b9e

test:
  secret_key_base: da7db445782c7d552ef17653b95a5322e6ab388ea183fce533a1991237d5b3d3644b6c19ef45dac4b123e36be92b4b40478011eb22aaa81e66833e76b350276b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
